
<div class="header1">
<h1><?= __('Bedankt voor uw bestelling bij PortofoonWEB!') ?></h1></div>

<conteiner class="conteiner1"> 
	<div class="column">
		<img src='<?php echo $this->getViewFileUrl('Devchannel_HelloWorld::images/fone.png'); ?>' alt="image-icon" width="120" height="250">
	</div>

<div class="column1">
	<div class="header3"><h3><?= __('Goed om te weten') ?></h3>
	</div>
	<div class="text1"><p><?= __('Bent u tevreden over het bestelproces like dan onze Facebook pagina of laat een review achter, zo maakt u ook nog eens kans op een leuke cadeau bon ter waarde van € 100,- Wilt u graag op de hoogte blijven van het laatste nieuws en speciale aanbiedingen meld u zich dan aan op onze nieuwsbrief.') ?></p></div>

<div class="header3"><h3><?= __('Wat gaat er nu gebeuren?') ?></h3>
	</div>
	<div class="text1"><p><?= __('Per email heeft u een bevestiging ontvangen van uw bestelling met Ordernummer [ordernummer]. Heeft u de bestelling op een werkdag voor 17:00 gedaan en betaald, dan gaan wij nu direct aan de slag om te zorgen dat u het morgen in huis heeft. Heeft u vragen over de bestelling neem dan contact met ons op 0512 – 745293 of stuur ons een email aan info@portofoonweb.nl.') ?></p></div>
	<div class="header3"><h3><?= __('Wist u dat?') ?></h3>
	</div>
	<div class="text1"><p><?= __('PortofoonWEB heeft sinds kort een fenomenaal nieuwe techniek genaamd Smart Portofoons. Een portofoon systeem met ongekende mogelijkheden en onbeperkt bereik! Klik op deze link voor meer informatie.') ?></p></div>
	
	<div class="conteinermini">
		<div><img src='<?php echo $this->getViewFileUrl('Devchannel_HelloWorld::images/Smartportofoon_Logo.png'); ?>' alt="image-icon" width="155" height="40"></div>
		<div><img src='<?php echo $this->getViewFileUrl('Devchannel_HelloWorld::images/facebook.png'); ?>' alt="image-icon" width="87" height="35"></div>
	</div>



</div>
<div class="column"></div>

</conteiner>

<div class="owl-carousel owl-theme">

	<div class="item"><img src='<?php echo $this->getViewFileUrl('Devchannel_HelloWorld::images/0.png'); ?>' alt="image-icon" width="70" height="42"></div>

<div class="item"><img src='<?php echo $this->getViewFileUrl('Devchannel_HelloWorld::images/1.png'); ?>' alt="image-icon" width="259" height="42"></div>

<div class="item"><img src='<?php echo $this->getViewFileUrl('Devchannel_HelloWorld::images/2.png'); ?>' alt="image-icon" width="100" height="42"></div>

<div class="item"><img src='<?php echo $this->getViewFileUrl('Devchannel_HelloWorld::images/3.png'); ?>' alt="image-icon" width="233" height="42"></div>

<div class="item"><img src='<?php echo $this->getViewFileUrl('Devchannel_HelloWorld::images/4.png'); ?>' alt="image-icon" width="87" height="42"></div>
</div>



<script type="text/x-magento-init">
	{
		"*": {
		"Devchannel_HelloWorld/js/carousel": {}
	}
	}

</script>